spring.application.name=blog

spring.config.import=classpath:postgres.properties,classpath:redis.properties,classpath:mail.properties

# 前端地址（用于邮件链接重定向）
app.frontend-url=http://localhost:5173

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=org.example.blog.handler